"$schema" = 'https://starship.rs/config-schema.json'

# Wait 30 milliseconds for starship to check files under the current directory.
scan_timeout = 30         # Default: 30
command_timeout = 500     # Default: 500
add_newline = true

format = """\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$hg_branch\
$hostname\
$line_break\
$character
"""

right_format = """
${custom.gcert_check}\
$time\
"""

[[battery.display]]
threshold = 10
style = "bold red"

[character]
success_symbol = "[](white) "
error_symbol = "[](bold red) "
vicmd_symbol = "[❮](bold green) "

[directory]
truncation_length = 8
truncate_to_repo = false
style = "bold blue"

[git_status]
style = "yellow"

[username]
disabled = true

[hostname]
style = "bright-yellow"
format = "[on $hostname ]($style)"

[java]
style = "red"
format ="[${symbol}(${version} )]($style)"

[kotlin]
format ="[${symbol}(${version} )]($style)"

[line_break]
disabled = false

[package]
disabled = false
display_private = false

[python]
python_binary = "python3"

[time]
disabled = false
use_12hr = true
utc_time_offset = "local"
style = "green"
