alias ls="eza --color=auto"
alias grep="grep --color=auto"
alias diff="diff --color=auto"
alias cp="cp -iv"
alias mv="mv -iv"
alias mkdir="mkdir -pv"
alias path='echo -e ${PATH//:/\\n}'
alias qfind="find . -name "
alias du="ncdu --color dark -rr -x --exclude .git --exclude node_modules"
alias shortdate="date +%Y%m%d%H%M%S"
